api/urls.py
from django.urls import path, include
from tastypie.api import Api
from api.models import UserResource 
# Post_commentResource, PostResource
# from api.models import CategoryResource, CourseResource
api = Api(api_name='v1')
api.register(UserResource())
# api.register(PostResource())
# api.register(Post_commentResource())

# api.register(CourseResource())
# api.register(CategoryResource())
urlpatterns = [
    path('', include(api.urls), name='index'),
    path('', include(api.urls), name='courses')
]

base/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('account/', include('account.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path 
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<slug:slug>/', views.single_post, name='single_post'),
    path('tagged/', views.tagged, name='tagged')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %}{% endblock %}</title>
    
</head>
<body class="body_all">
    <div class="header_m">
        <div class="header_left">
            <a href={% url "blog:index" %} class="header-brand">Blogs</a> 
        </div>
        <div class="header_search">
            <span class="icon_search">
                <i class="fa fa-search">
    
                </i>
                Поиск
            </span>
        </div>
        <div class="header_right">
            <span class='header-text'>
                {% comment %} <a> {{ last_page }}</a> {% endcomment %}
                {% if user.is_authenticated %}
                {% load static %}
                <img src="{% static userInfo.photo.url %}" alt="My image" onclick="oncl()" class="img_icon">
                {% else %}
                <a href={% url "login"  %} class="header_menu">Login</a>
                {% endif %}
                <a href="/admin/" class="header_menu" target="_blank">Admin</a>
                <a href="/api/v1/" class="header_menu" target="_blank">API</a>
            </span> 
            <div class="header_pen">
                <i class="fa fa-pencil">

                </i>
            </div> 
        </div>
    </div>
    <br>
    {% if user.is_authenticated %}
    <div class ="header_menu_burger">
        <a href={% url "account" %} class="header_menu">{{ user.get_username }}</a>
    </div>
    {% endif %}

    
    <div class="body_down">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static "JavaScript/main.js" %}"></script>
</body>
</html>

templates/image_test.html
{% extends 'base.html' %}

{% block title %}All test{% endblock %} 

{% block content %}
{% load static %}
<img src="{% static "media/default.jpg" %}" alt="My image">
{% endblock %} 